Combine interfaces
BPChain/api-server pull request #12
Opened 2017-11-28 16:10 UTC by tom-lichtenstein

2017-11-28 17:35 UTC, fyndalf requested changes

2017-11-28 17:35 UTC, fyndalf commented on src/frontendInterface.js
> +}
Insert trailing newline

2017-11-29 10:08 UTC, simsieg requested changes

2017-11-29 10:08 UTC, simsieg commented on components/privateChains/backendListener.js
> +            log.info('Successfully stored input with id: ' + savedModel.id)
Template string

2017-11-29 10:09 UTC, fyndalf approved these changes

2017-11-29 10:15 UTC, simsieg approved these changes

2017-11-29 10:15 UTC, merged